version: 2
jobs:
  buildandtest:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make build
      - run: make ci

  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  any-commit:
    jobs:
      - buildandtest:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
