version: 2
jobs:
  buildandtest:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          keys:
            - v${CACHE_VERSION}-pkg-cache
      - run: make install-build-deps
      - run: dep ensure
      - run: make build
      - run: make ci
      - save_cache:
          key: v${CACHE_VERSION}-pkg-cache
          paths:
            - ~/.cache/go-build

  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make install-build-deps
      - run: dep ensure
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  any-commit:
    jobs:
      - buildandtest:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
