/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/serverless-operator/serverless-operator/pkg/apis/serverlessrelease/v1alpha1"
	scheme "github.com/serverless-operator/serverless-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServerlessReleasesGetter has a method to return a ServerlessReleaseInterface.
// A group's client should implement this interface.
type ServerlessReleasesGetter interface {
	ServerlessReleases(namespace string) ServerlessReleaseInterface
}

// ServerlessReleaseInterface has methods to work with ServerlessRelease resources.
type ServerlessReleaseInterface interface {
	Create(*v1alpha1.ServerlessRelease) (*v1alpha1.ServerlessRelease, error)
	Update(*v1alpha1.ServerlessRelease) (*v1alpha1.ServerlessRelease, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ServerlessRelease, error)
	List(opts v1.ListOptions) (*v1alpha1.ServerlessReleaseList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServerlessRelease, err error)
	ServerlessReleaseExpansion
}

// serverlessReleases implements ServerlessReleaseInterface
type serverlessReleases struct {
	client rest.Interface
	ns     string
}

// newServerlessReleases returns a ServerlessReleases
func newServerlessReleases(c *ReleaseV1alpha1Client, namespace string) *serverlessReleases {
	return &serverlessReleases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serverlessRelease, and returns the corresponding serverlessRelease object, and an error if there is any.
func (c *serverlessReleases) Get(name string, options v1.GetOptions) (result *v1alpha1.ServerlessRelease, err error) {
	result = &v1alpha1.ServerlessRelease{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serverlessreleases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServerlessReleases that match those selectors.
func (c *serverlessReleases) List(opts v1.ListOptions) (result *v1alpha1.ServerlessReleaseList, err error) {
	result = &v1alpha1.ServerlessReleaseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serverlessreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serverlessReleases.
func (c *serverlessReleases) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serverlessreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a serverlessRelease and creates it.  Returns the server's representation of the serverlessRelease, and an error, if there is any.
func (c *serverlessReleases) Create(serverlessRelease *v1alpha1.ServerlessRelease) (result *v1alpha1.ServerlessRelease, err error) {
	result = &v1alpha1.ServerlessRelease{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serverlessreleases").
		Body(serverlessRelease).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serverlessRelease and updates it. Returns the server's representation of the serverlessRelease, and an error, if there is any.
func (c *serverlessReleases) Update(serverlessRelease *v1alpha1.ServerlessRelease) (result *v1alpha1.ServerlessRelease, err error) {
	result = &v1alpha1.ServerlessRelease{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serverlessreleases").
		Name(serverlessRelease.Name).
		Body(serverlessRelease).
		Do().
		Into(result)
	return
}

// Delete takes name of the serverlessRelease and deletes it. Returns an error if one occurs.
func (c *serverlessReleases) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serverlessreleases").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serverlessReleases) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serverlessreleases").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serverlessRelease.
func (c *serverlessReleases) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServerlessRelease, err error) {
	result = &v1alpha1.ServerlessRelease{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serverlessreleases").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
