apiVersion: serverless-operator.io/v1alpha1
kind: ServerlessRelease
metadata:
  name: example-serverless-app
spec:
  packagePath: test-package.zip
  releaseName: testing-v0.0.1
  stage: staging
  region: eu-west-1
  verbose: false
  env:
    - name: MYVAR
      value: somevalue
    - name: MYSECRET_VAR
      valueFrom:
        secretKeyRef:
            name: sample1-secrets
            key: username
    - name: MYCONFIG_VAR
      valueFrom:
        configMapKeyRef:
            name: sample1-config
            key: region

