/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/serverless-operator/serverless-operator/pkg/apis/serverlessrelease/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServerlessReleases implements ServerlessReleaseInterface
type FakeServerlessReleases struct {
	Fake *FakeReleaseV1alpha1
	ns   string
}

var serverlessreleasesResource = schema.GroupVersionResource{Group: "release.serverless-operator", Version: "v1alpha1", Resource: "serverlessreleases"}

var serverlessreleasesKind = schema.GroupVersionKind{Group: "release.serverless-operator", Version: "v1alpha1", Kind: "ServerlessRelease"}

// Get takes name of the serverlessRelease, and returns the corresponding serverlessRelease object, and an error if there is any.
func (c *FakeServerlessReleases) Get(name string, options v1.GetOptions) (result *v1alpha1.ServerlessRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serverlessreleasesResource, c.ns, name), &v1alpha1.ServerlessRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessRelease), err
}

// List takes label and field selectors, and returns the list of ServerlessReleases that match those selectors.
func (c *FakeServerlessReleases) List(opts v1.ListOptions) (result *v1alpha1.ServerlessReleaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serverlessreleasesResource, serverlessreleasesKind, c.ns, opts), &v1alpha1.ServerlessReleaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServerlessReleaseList{ListMeta: obj.(*v1alpha1.ServerlessReleaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServerlessReleaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serverlessReleases.
func (c *FakeServerlessReleases) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serverlessreleasesResource, c.ns, opts))

}

// Create takes the representation of a serverlessRelease and creates it.  Returns the server's representation of the serverlessRelease, and an error, if there is any.
func (c *FakeServerlessReleases) Create(serverlessRelease *v1alpha1.ServerlessRelease) (result *v1alpha1.ServerlessRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serverlessreleasesResource, c.ns, serverlessRelease), &v1alpha1.ServerlessRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessRelease), err
}

// Update takes the representation of a serverlessRelease and updates it. Returns the server's representation of the serverlessRelease, and an error, if there is any.
func (c *FakeServerlessReleases) Update(serverlessRelease *v1alpha1.ServerlessRelease) (result *v1alpha1.ServerlessRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serverlessreleasesResource, c.ns, serverlessRelease), &v1alpha1.ServerlessRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessRelease), err
}

// Delete takes name of the serverlessRelease and deletes it. Returns an error if one occurs.
func (c *FakeServerlessReleases) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serverlessreleasesResource, c.ns, name), &v1alpha1.ServerlessRelease{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServerlessReleases) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serverlessreleasesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServerlessReleaseList{})
	return err
}

// Patch applies the patch and returns the patched serverlessRelease.
func (c *FakeServerlessReleases) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServerlessRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serverlessreleasesResource, c.ns, name, data, subresources...), &v1alpha1.ServerlessRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessRelease), err
}
